### PR TITLE
Add extensions to specify custom Go types

### PR DESCRIPTION
**Pull request by leejuyuu**
Inspired by deepmap/oapi-codegen.
Add `x-go-type` and `x-go-type-import` for specifying custom Go types for generating corresponding Go code for the Schema Objects. Add tests to check the results.

Closes https://github.com/lerenn/asyncapi-codegen/issues/48.

### CODE REVIEW

**Comment by lerenn** [comment]
Hello Leejuyuu ! Sorry, I didn't see the pull request message in my emails :/

I'll take a depper look today at your code, it looks really great on a first look.
Thank you very much!

**Comment by lerenn** [comment]
I took a look in your code and it is really great work! Especially the custom imports part which is really interesting and can be reused later.

I took the liberty to solve the conflict with the README and I'll merge it.

Thanks again for sharing your work :pray:

**Comment by lerenn** [comment]
Tagged as v0.18.0

**Comment by leejuyuu** [comment]
Thanks for merging!

**Pull request merged**
